export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const HOME_ROUTE = '/'
export const ORGANIZATION_ROUTE = '/organization'
export const EVENT_ROUTE = '/event'
export const VOLUNTEER_ROUTE = '/volunteer'
export const PROBLEM_ROUTE = '/problem'